version: "3.8"

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"

    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=dbase



  pgadmin:
    image: dpage/pgadmin4

    environment:
      PGADMIN_DEFAULT_EMAIL: "excelpro.goo@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    
    ports:
      - "80:80"
    depends_on:
      - postgres

